name: Run CI checks

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, reopened]
jobs:
  ci-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['5.0.9']

    steps:
    - name: Check labels
      uses: jesusvasquez333/verify-pr-label-action@v1.4.0
      with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'patch, minor, major'
          pull-request-number: '${{ github.event.pull_request.number }}'
    - name: Start MongoDB
      uses: MongoCamp/mongodb-github-action@1.0.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: curl http://localhost:27017

    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'
    - run: poetry install
    - name: Lint
      run: poetry run ruff .
    - name: Test
      run: poetry run pytest