name: Run CI checks

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, reopened]
jobs:
  ci-checks:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        mongodb-version: ['5.0.9']

    steps:
    - name: Check PR labels
      run: |
        if [[ !contains(${{github.event.pull_request.labels.*.name}}, 'patch') ]]; then
          echo "Pull request must have at least one of the following labels: patch."
          exit 1
        fi
    - name: Start MongoDB
      uses: MongoCamp/mongodb-github-action@1.0.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: curl http://localhost:27017

    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'
    - run: poetry install
    - name: Lint
      run: poetry run ruff .
    - name: Test
      run: poetry run pytest