name: Run CI checks

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, reopened]
jobs:
  check-labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  ci-checks:
    needs: check-labels
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        mongodb-version: ['5.0.9']

    steps:
    - name: Start MongoDB
      uses: MongoCamp/mongodb-github-action@1.0.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: curl http://localhost:27017

    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'
    - run: poetry install
    - name: Lint
      run: poetry run ruff .
    - name: Test
      run: poetry run pytest

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
