name: Release

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged
    
    steps:
      - name: Gen version number
        id: gen-version
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: poetry install
      - run: git config user.name "${{ github.actor }}"
      - run: git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Remove 'v' prefix
        run: VERSION=$(echo "${{ steps.gen-version.outputs.tag }}" | sed 's/^v//')

      - name: Update pyproject file $VERSION
        run: |
          poetry version "$VERSION"
          git commit pyproject.toml -m "[skip ci] Bump to version $VERSION"
          git push
      
      - name: Create a new github release
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
